### ISSUE TITLE
Ampersand not escaped in exported XML

### ISSUE THREAD

**Issue by moonthug** [danmasta/mocha-sonar#2]
If a (mocha) test suite title contains an & (ampersand), it is not escaped properly when the reporter generates XML.

As a result Sonarqube is unable to import the XML.

i.e.
```
Breaks:

it('should set the `username` & `password` from the options', () => {
   ...
});
```

**Comment by danmasta** [comment]
Nice catch, fixed here: https://github.com/danmasta/mocha-sonar/commit/9bbcc797c229f6b99b0d22645378149dd560d5c2
